# buildspec.yml
version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js version 20 ..."
      - n 20.19.2
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - echo "Running Playwright tests..."
      - npx playwright test --reporter=html

reports:
  playwright:
    files:
      - index.html
    base-directory: playwright-report
    discard-paths: no
    file-format: HTML

artifacts:
  files:
    - playwright-report/**/*
    - test-results/**/*
  discard-paths: no