version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - echo "Installing Playwright browsers..."
      - npx playwright install --with-deps

  build:
    commands:
      - echo "Running Playwright tests..."
      - npm test || true  # Continúa aunque fallen los tests

  post_build:
    commands:
      - echo "Test execution completed"

artifacts:
  files:
    - 'playwright-report/**/*'
  name: playwright-report-$(date +%Y%m%d-%H%M%S)

reports:
  playwright-results:
    files:
      - 'playwright-report/**/*'
    file-format: 'JUNITXML'  # Si tienes reportes JUnit
    base-directory: 'playwright-report'