# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npx playwright install --with-deps chromium
      
  build:
    commands:
      - echo "Running Playwright tests..."
      - npx playwright test
      
  post_build:
    commands:
      - echo "Tests completed"

artifacts:
  files:
    - 'playwright-report/**/*'
    - 'test-results/**/*'
  name: playwright-reports-$(date +%Y%m%d-%H%M%S)

reports:
  playwright:
    files:
      - 'playwright-report/index.html'
    file-format: 'HTML'